name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Verify
    runs-on: macos-15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Swift Version
        run: swift --version

      - name: Build Package
        run: swift build -c release
